language: php

php:
  - 5.4.8
  - 5.5.0
  - 5.6.3

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source
  - phpenv config-add myconfig.ini

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml --configuration tests/phpunit.xml.dist tests

after_script:
  - php vendor/bin/coveralls -v
